// @flow
const columnList = [
  'Work Order #',
  'Created On',
  'Due Date',
  'Next Due Date',
  'End Due Date',
  'Updated On',
  'Completed On',
  'Work Order Title',
  'Work Order Description',
  'Cost',
  'Time',
  'Status',
  'Category',
  'Reschedule Based On Completion',
  'Repeating Schedule',
  'Root Work Order Exists',
  'Asset ID',
  'Asset Name',
  'Asset Category',
  'Asset Area',
  'Asset Barcode',
  'Location Name',
  'Location Address',
  'Location ID',
  'Completed By',
  'Completed By ID',
  'Requires Signature',
  'Signature Image',
  'Assigned By',
  'Assigned By ID',
  'Assigned To',
  'Assigned To ID',
  'Team Assigned',
  'Team Assigned ID',
  'Parts',
  'Purchase Orders',
  'Parts Cost',
  'Total Cost',
  'Estimated duration',
  'Updates',
  'Priority',
  'Archived Status',
  'Images',
  'Checklist ID',
  'Task Data',
  'Task Images',
  'Additional Workers',
  'Additional Worker IDs',
  'Requested By',
  'Requested By ID',
  'Requested By Email Address',
  'Part IDs',
  'Part Quantities',
  'File IDs',
];

export default columnList;
